trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.5.0'
  workingDirectory: '$(System.DefaultWorkingDirectory)/Project1_hub_N_spoke'

stages:
- stage: Terraform_Plan
  jobs:
  - job: Plan

    steps:

    # Install Terraform
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: $(terraformVersion)

    # Terraform Init + Plan with Azure Auth
    - script: |
        export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
        export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
        export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
        export ARM_TENANT_ID=$(ARM_TENANT_ID)

        terraform init
        terraform plan
      workingDirectory: $(workingDirectory)
      displayName: "Terraform Init & Plan"